### PR TITLE
fixes #1 add Services tag to instances

### LINKED ISSUE #1: cloudformation template needs a Services tag to be assigned to instances
This is for stackdriver so we can group things better, see: 
https://github.com/mozilla-services/svcops/issues/48

### PR DESCRIPTION
**Pull request by mostlygeek**
@gene1wood please r?

### CODE REVIEW

**Comment by gene1wood** [comment]
Looks good, what is this new tag? I don't see it here : https://mana.mozilla.org/wiki/display/SVCOPS/AWS+EC2+Instance+Tags
How is it used?

**Comment by mostlygeek** [comment]
It's not a standard tag, it's basically just a space delimited string that we can use in Stackdriver to make grouping/sub-grouping easier. Other than that it shouldn't have any other operational usage.

**Comment by mostlygeek** [comment]
Also trying it out first to see if it is a good pattern for making life easier

**Comment by gene1wood** [comment]
Whoops, I didn't trace back to #1 and then read https://github.com/mozilla-services/svcops/issues/48

**Pull request merged**
